[build]
  command = "bun i && bun run build && bun run copy"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; object-src 'none'; frame-ancestors 'none'; require-trusted-types-for 'script';"
    Cross-Origin-Opener-Policy = "same-origin"
    X-Frame-Options = "DENY"
